ServerResponse {
      _events: [Object: null prototype] { finish: [Function: bound resOnFinish] },
      _eventsCount: 1,
          _maxListeners: undefined,
              outputData: [],
                  outputSize: 0,
                      writable: true,
                          destroyed: false,
                              _last: false,
                                  chunkedEncoding: false,
                                      shouldKeepAlive: true,
                                          maxRequestsOnConnectionReached: false,
                                              _defaultKeepAlive: true,
                                                  useChunkedEncodingByDefault: true,
                                                      sendDate: true,
                                                          _removedConnection: false,
                                                              _removedContLen: false,
                                                                  _removedTE: false,
                                                                      strictContentLength: false,
                                                                          _contentLength: null,
                                                                              _hasBody: true,
                                                                                  _trailer: '',
                                                                                      finished: false,
                                                                                          _headerSent: false,
                                                                                              _closed: false,
                                                                                                  socket: <ref * 1 > Socket {
            connecting: false,
                _hadError: false,
                    _parent: null,
                        _host: null,
                            _closeAfterHandlingError: false,
                                _events: {
                                      close: [Array],
                                          error: [Function: socketOnError],
                                              prefinish: undefined,
                                                  finish: undefined,
                                                      drain: [Function: bound socketOnDrain],
                                                          data: [Function: bound socketOnData],
                                                              end: [Array],
                                                                  readable: undefined,
                                                                      timeout: [Function: socketOnTimeout],
                                                                          resume: [Function: onSocketResume],
                                                                              pause: [Function: onSocketPause]
                                                                        [0]
                            },
            _readableState: ReadableState {
                  highWaterMark: 16384,
                      buffer: [],
                          bufferIndex: 0,
                              length: 0,
                                  pipes: [],
                                      awaitDrainWriters: null,
                                    [0][Symbol(kState)]: 193997060
                                    [0]
        },
            _writableState: WritableState {
                  highWaterMark: 16384,
                      length: 0,
                          corked: 0,
                              onwrite: [Function: bound onwrite],
                                  writelen: 0,
                                      bufferedIndex: 0,
                                          pendingcb: 0,
                                        [0][Symbol(kState)]: 17563908,
                                            [0][Symbol(kBufferedValue)]: null,
                                                [0][Symbol(kWriteCbValue)]: [Function: bound onFinish],
                                                    [0][Symbol(kAfterWriteTickInfoValue)]: null
                                                    [0]
        },
            allowHalfOpen: true,
                _maxListeners: undefined,
                    _eventsCount: 8,
                        _sockname: null,
                            _pendingData: null,
                                _pendingEncoding: '',
                                    server: Server {
                  maxHeaderSize: undefined,
                      insecureHTTPParser: undefined,
                          requestTimeout: 300000,
                              headersTimeout: 60000,
                                  keepAliveTimeout: 5000,
                                      connectionsCheckingInterval: 30000,
                                          requireHostHeader: true,
                                              joinDuplicateHeaders: undefined,
                                                  rejectNonStandardBodyWrites: false,
                                                      _events: [Object: null prototype],
                                                          _eventsCount: 3,
                                                              _maxListeners: undefined,
                                                                  _connections: 4,
                                                                      _handle: [TCP],
                                                                          _usingWorkers: false,
                                                                              _workers: [],
                                                                                  _unref: false,
                                                                                      allowHalfOpen: true,
                                                                                          pauseOnConnect: false,
                                                                                              noDelay: true,
                                                                                                  keepAlive: false,
                                                                                                      keepAliveInitialDelay: 0,
                                                                                                          highWaterMark: 16384,
                                                                                                              httpAllowHalfOpen: false,
                                                                                                                  timeout: 0,
                                                                                                                      maxHeadersCount: null,
                                                                                                                          maxRequestsPerSocket: 0,
                                                                                                                              _connectionKey: '6::::5000',
                                                                                                                            [0][Symbol(IncomingMessage)]: [Function: IncomingMessage],
                                                                                                                                [0][Symbol(ServerResponse)]: [Function: ServerResponse],
                                                                                                                                    [0][Symbol(shapeMode)]: false,
                                                                                                                                        [0][Symbol(kCapture)]: false,
                                                                                                                                            [0][Symbol(async_id_symbol)]: 12,
                                                                                                                                                [0][Symbol(kUniqueHeaders)]: null,
                                                                                                                                                    [0][Symbol(http.server.connections)]: ConnectionsList { },
            [0][Symbol(http.server.connectionsCheckingInterval)]: Timeout {
                        _idleTimeout: 30000,
                            _idlePrev: [TimersList],
                                _idleNext: [TimersList],
                                    _idleStart: 500,
                                        _onTimeout: [Function: bound checkConnections],
                                            _timerArgs: undefined,
                                                _repeat: 30000,
                                                    _destroyed: false,
                                                [0][Symbol(refed)]: false,
                                                    [0][Symbol(kHasPrimitive)]: false,
                                                        [0][Symbol(asyncId)]: 15,
                                                            [0][Symbol(triggerId)]: 13
                                                            [0]
            }
            [0]
        },
            _server: Server {
                  maxHeaderSize: undefined,
                      insecureHTTPParser: undefined,
                          requestTimeout: 300000,
                              headersTimeout: 60000,
                                  keepAliveTimeout: 5000,
                                      connectionsCheckingInterval: 30000,
                                          requireHostHeader: true,
                                              joinDuplicateHeaders: undefined,
                                                  rejectNonStandardBodyWrites: false,
                                                      _events: [Object: null prototype],
                                                          _eventsCount: 3,
                                                              _maxListeners: undefined,
                                                                  _connections: 4,
                                                                      _handle: [TCP],
                                                                          _usingWorkers: false,
                                                                              _workers: [],
                                                                                  _unref: false,
                                                                                      allowHalfOpen: true,
                                                                                          pauseOnConnect: false,
                                                                                              noDelay: true,
                                                                                                  keepAlive: false,
                                                                                                      keepAliveInitialDelay: 0,
                                                                                                          highWaterMark: 16384,
                                                                                                              httpAllowHalfOpen: false,
                                                                                                                  timeout: 0,
                                                                                                                      maxHeadersCount: null,
                                                                                                                          maxRequestsPerSocket: 0,
                                                                                                                              _connectionKey: '6::::5000',
                                                                                                                            [0][Symbol(IncomingMessage)]: [Function: IncomingMessage],
                                                                                                                                [0][Symbol(ServerResponse)]: [Function: ServerResponse],
                                                                                                                                    [0][Symbol(shapeMode)]: false,
                                                                                                                                        [0][Symbol(kCapture)]: false,
                                                                                                                                            [0][Symbol(async_id_symbol)]: 12,
                                                                                                                                                [0][Symbol(kUniqueHeaders)]: null,
                                                                                                                                                    [0][Symbol(http.server.connections)]: ConnectionsList { },
            [0][Symbol(http.server.connectionsCheckingInterval)]: Timeout {
                        _idleTimeout: 30000,
                            _idlePrev: [TimersList],
                                _idleNext: [TimersList],
                                    _idleStart: 500,
                                        _onTimeout: [Function: bound checkConnections],
                                            _timerArgs: undefined,
                                                _repeat: 30000,
                                                    _destroyed: false,
                                                [0][Symbol(refed)]: false,
                                                    [0][Symbol(kHasPrimitive)]: false,
                                                        [0][Symbol(asyncId)]: 15,
                                                            [0][Symbol(triggerId)]: 13
                                                            [0]
            }
            [0]
        },
            parser: HTTPParser {
                  '0': null,
                      '1': [Function: parserOnHeaders],
                          '2': [Function: parserOnHeadersComplete],
                              '3': [Function: parserOnBody],
                                  '4': [Function: parserOnMessageComplete],
                                      '5': [Function: bound onParserExecute],
                                          '6': [Function: bound onParserTimeout],
                                              _headers: [],
                                                  _url: '',
                                                      socket: [Circular * 1],
                                                          incoming: [IncomingMessage],
                                                              outgoing: null,
                                                                  maxHeaderPairs: 2000,
                                                                      _consumed: true,
                                                                          onIncoming: [Function: bound parserOnIncoming],
                                                                              joinDuplicateHeaders: null,
                                                                            [0][Symbol(resource_symbol)]: [HTTPServerAsyncResource]
                                                                            [0]
        },
            on: [Function: socketListenerWrap],
                addListener: [Function: socketListenerWrap],
                    prependListener: [Function: socketListenerWrap],
                        setEncoding: [Function: socketSetEncoding],
                            _paused: false,
                            _httpMessage: [Circular * 2],
                                    timeout: 0,
                                    [0][Symbol(async_id_symbol)]: 267,
                                        [0][Symbol(kHandle)]: TCP {
                  reading: true,
                      onconnection: null,
                          _consumed: true,
                        [0][Symbol(owner_symbol)]: [Circular * 1]
                        [0]
        },
        [0][Symbol(lastWriteQueueSize)]: 0,
            [0][Symbol(timeout)]: Timeout {
                  _idleTimeout: -1,
                      _idlePrev: null,
                          _idleNext: null,
                              _idleStart: 4347,
                                  _onTimeout: null,
                                      _timerArgs: undefined,
                                          _repeat: null,
                                              _destroyed: true,
                                            [0][Symbol(refed)]: false,
                                                [0][Symbol(kHasPrimitive)]: false,
                                                    [0][Symbol(asyncId)]: 286,
                                                        [0][Symbol(triggerId)]: 283
                                                        [0]
        },
        [0][Symbol(kBuffer)]: null,
            [0][Symbol(kBufferCb)]: null,
                [0][Symbol(kBufferGen)]: null,
                    [0][Symbol(shapeMode)]: true,
                        [0][Symbol(kCapture)]: false,
                            [0][Symbol(kSetNoDelay)]: true,
                                [0][Symbol(kSetKeepAlive)]: false,
                                    [0][Symbol(kSetKeepAliveInitialDelay)]: 0,
                                        [0][Symbol(kBytesRead)]: 0,
                                            [0][Symbol(kBytesWritten)]: 0
                                            [0]
    },
      _header: null,
          _keepAliveTimeout: 5000,
              _onPendingData: [Function: bound updateOutgoingData],
                  req: IncomingMessage {
            _events: {
                  close: undefined,
                      error: undefined,
                          data: undefined,
                              end: undefined,
                                  readable: undefined,
                                      aborted: undefined
                                [0]
        },
            _readableState: ReadableState {
                  highWaterMark: 16384,
                      buffer: [],
                          bufferIndex: 0,
                              length: 0,
                                  pipes: [],
                                      awaitDrainWriters: null,
                                    [0][Symbol(kState)]: 60295036
                                    [0]
        },
            _maxListeners: undefined,
                socket: <ref * 1 > Socket {
                  connecting: false,
                      _hadError: false,
                          _parent: null,
                              _host: null,
                                  _closeAfterHandlingError: false,
                                      _events: [Object],
                                          _readableState: [ReadableState],
                                              _writableState: [WritableState],
                                                  allowHalfOpen: true,
                                                      _maxListeners: undefined,
                                                          _eventsCount: 8,
                                                              _sockname: null,
                                                                  _pendingData: null,
                                                                      _pendingEncoding: '',
                                                                          server: [Server],
                                                                              _server: [Server],
                                                                                  parser: [HTTPParser],
                                                                                      on: [Function: socketListenerWrap],
                                                                                          addListener: [Function: socketListenerWrap],
                                                                                              prependListener: [Function: socketListenerWrap],
                                                                                                  setEncoding: [Function: socketSetEncoding],
                                                                                                      _paused: false,
                                                                                                          _httpMessage: [Circular * 2],
                                                                                                              timeout: 0,
                                                                                                            [0][Symbol(async_id_symbol)]: 267,
                                                                                                                [0][Symbol(kHandle)]: [TCP],
                                                                                                                    [0][Symbol(lastWriteQueueSize)]: 0,
                                                                                                                        [0][Symbol(timeout)]: Timeout {
                        _idleTimeout: -1,
                            _idlePrev: null,
                                _idleNext: null,
                                    _idleStart: 4347,
                                        _onTimeout: null,
                                            _timerArgs: undefined,
                                                _repeat: null,
                                                    _destroyed: true,
                                                [0][Symbol(refed)]: false,
                                                    [0][Symbol(kHasPrimitive)]: false,
                                                        [0][Symbol(asyncId)]: 286,
                                                            [0][Symbol(triggerId)]: 283
                                                            [0]
            },
            [0][Symbol(kBuffer)]: null,
                [0][Symbol(kBufferCb)]: null,
                    [0][Symbol(kBufferGen)]: null,
                        [0][Symbol(shapeMode)]: true,
                            [0][Symbol(kCapture)]: false,
                                [0][Symbol(kSetNoDelay)]: true,
                                    [0][Symbol(kSetKeepAlive)]: false,
                                        [0][Symbol(kSetKeepAliveInitialDelay)]: 0,
                                            [0][Symbol(kBytesRead)]: 0,
                                                [0][Symbol(kBytesWritten)]: 0
                                                [0]
        },
            httpVersionMajor: 1,
                httpVersionMinor: 1,
                    httpVersion: '1.1',
                        complete: true,
                            rawHeaders: [
                                  'Host',
                                  'localhost:5000',
                                  'Connection',
                                  'keep-alive',
                                  'Content-Length',
                                  '59',
                                  'Cache-Control',
                                  'max-age=0',
                                  'sec-ch-ua',
                                  '"Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"',
                                  'sec-ch-ua-mobile',
                                  '?0',
                                  'sec-ch-ua-platform',
                                  '"macOS"',
                                  'Upgrade-Insecure-Requests',
                                  '1',
                                  'Origin',
                                  'http://localhost:5000',
                                  'Content-Type',
                                  'application/x-www-form-urlencoded',
                                  'User-Agent',
                                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
                                  'Accept',
                                  'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
                                  'Sec-Fetch-Site',
                                  'same-origin',
                                  'Sec-Fetch-Mode',
                                  'navigate',
                                  'Sec-Fetch-User',
                                  '?1',
                                  'Sec-Fetch-Dest',
                                  'document',
                                  'Referer',
                                  'http://localhost:5000/editar-perfil',
                                  'Accept-Encoding',
                                  'gzip, deflate, br, zstd',
                                  'Accept-Language',
                                  'es-419,es;q=0.9',
                                  'Cookie',
                                  'llavesecreta=s%3AGev6rQGoAych1bVULz7PpGYHg77FGg4f.tGxgkPI5r46xSkFnxDSyNdCflM3SADpKS1QqJ9GAZfg'
                            [0]],
                                rawTrailers: [],
                                    joinDuplicateHeaders: null,
                                        aborted: false,
                                            upgrade: false,
                                                url: '/editar-perfil',
                                                    method: 'POST',
                                                        statusCode: null,
                                                            statusMessage: null,
                                                                client: <ref * 1 > Socket {
                  connecting: false,
                      _hadError: false,
                          _parent: null,
                              _host: null,
                                  _closeAfterHandlingError: false,
                                      _events: [Object],
                                          _readableState: [ReadableState],
                                              _writableState: [WritableState],
                                                  allowHalfOpen: true,
                                                      _maxListeners: undefined,
                                                          _eventsCount: 8,
                                                              _sockname: null,
                                                                  _pendingData: null,
                                                                      _pendingEncoding: '',
                                                                          server: [Server],
                                                                              _server: [Server],
                                                                                  parser: [HTTPParser],
                                                                                      on: [Function: socketListenerWrap],
                                                                                          addListener: [Function: socketListenerWrap],
                                                                                              prependListener: [Function: socketListenerWrap],
                                                                                                  setEncoding: [Function: socketSetEncoding],
                                                                                                      _paused: false,
                                                                                                          _httpMessage: [Circular * 2],
                                                                                                              timeout: 0,
                                                                                                            [0][Symbol(async_id_symbol)]: 267,
                                                                                                                [0][Symbol(kHandle)]: [TCP],
                                                                                                                    [0][Symbol(lastWriteQueueSize)]: 0,
                                                                                                                        [0][Symbol(timeout)]: Timeout {
                        _idleTimeout: -1,
                            _idlePrev: null,
                                _idleNext: null,
                                    _idleStart: 4347,
                                        _onTimeout: null,
                                            _timerArgs: undefined,
                                                _repeat: null,
                                                    _destroyed: true,
                                                [0][Symbol(refed)]: false,
                                                    [0][Symbol(kHasPrimitive)]: false,
                                                        [0][Symbol(asyncId)]: 286,
                                                            [Symbol(triggerId)]: 283
                                                            [0]
            },
            [0][Symbol(kBuffer)]: null,
                [0][Symbol(kBufferCb)]: null,
                    [0][Symbol(kBufferGen)]: null,
                        [0][Symbol(shapeMode)]: true,
                            [0][Symbol(kCapture)]: false,
                                [0][Symbol(kSetNoDelay)]: true,
                                    [0][Symbol(kSetKeepAlive)]: false,
                                        [0][Symbol(kSetKeepAliveInitialDelay)]: 0,
                                            [0][Symbol(kBytesRead)]: 0,
                                                [0][Symbol(kBytesWritten)]: 0
                                                [0]
        },
            _consuming: true,
                _dumped: false,
                    next: [Function: next],
                        baseUrl: '',
                            originalUrl: '/editar-perfil',
                                _parsedUrl: Url {
                  protocol: null,
                      slashes: null,
                          auth: null,
                              host: null,
                                  port: null,
                                      hostname: null,
                                          hash: null,
                                              search: null,
                                                  query: null,
                                                      pathname: '/editar-perfil',
                                                          path: '/editar-perfil',
                                                              href: '/editar-perfil',
                                                                  _raw: '/editar-perfil'
                                                            [0]
        },
            params: { },
            query: { },
            res: [Circular * 2],
                body: {
                      nombre: 'Antonio',
                          email: 'antonio.torres@milenio.com',
                              password: ''
                        [0]
            },
            _body: true,
                length: undefined,
                    _eventsCount: 0,
                        _validationCustomMethods: { sanitizers: { }, validators: { } },
            _validationErrors: [],
                _asyncValidationErrors: [],
                    validationErrors: [Function(anonymous)],
                        asyncValidationErrors: [Function(anonymous)],
                            getValidationResult: [Function(anonymous)],
                                sanitizeBody: [Function(anonymous)],
                                    sanitizeParams: [Function(anonymous)],
                                        sanitizeQuery: [Function(anonymous)],
                                            sanitizeCookies: [Function(anonymous)],
                                                sanitizeHeaders: [Function(anonymous)],
                                                    sanitize: [Function(anonymous)],
                                                        checkBody: [Function(anonymous)],
                                                            checkParams: [Function(anonymous)],
                                                                checkQuery: [Function(anonymous)],
                                                                    checkCookies: [Function(anonymous)],
                                                                        checkHeaders: [Function(anonymous)],
                                                                            check: [Function(anonymous)],
                                                                                filter: [Function(anonymous)],
                                                                                    assert: [Function(anonymous)],
                                                                                        validate: [Function(anonymous)],
                                                                                            secret: undefined,
                                                                                                cookies: {
                                                                                                      llavesecreta: 's:Gev6rQGoAych1bVULz7PpGYHg77FGg4f.tGxgkPI5r46xSkFnxDSyNdCflM3SADpKS1QqJ9GAZfg'
                                                                                                [0]
                                                                                            },
            signedCookies: [Object: null prototype] { },
            _parsedOriginalUrl: Url {
                  protocol: null,
                      slashes: null,
                          auth: null,
                              host: null,
                                  port: null,
                                      hostname: null,
                                          hash: null,
                                              search: null,
                                                  query: null,
                                                      pathname: '/editar-perfil',
                                                          path: '/editar-perfil',
                                                              href: '/editar-perfil',
                                                                  _raw: '/editar-perfil'
                                                            [0]
        },
            sessionStore: MongoStore {
                  _events: [Object: null prototype],
                      _eventsCount: 2,
                          _maxListeners: undefined,
                              ttl: 1209600,
                                  collectionName: 'sessions',
                                      autoRemove: 'native',
                                          autoRemoveInterval: 10,
                                              transformFunctions: [Object],
                                                  options: [Object],
                                                      state: 'connected',
                                                          generate: [Function(anonymous)],
                                                              db: [Db],
                                                                  collectionReadyPromise: [Promise],
                                                                      collection: [Collection],
                                                                    [0][Symbol(shapeMode)]: false,
                                                                        [0][Symbol(kCapture)]: false
                                                                        [0]
        },
            sessionID: 'Gev6rQGoAych1bVULz7PpGYHg77FGg4f',
                session: Session { cookie: [Object], passport: [Object], flash: { } },
            logIn: [Function(anonymous)],
                login: [Function(anonymous)],
                    logOut: [Function(anonymous)],
                        logout: [Function(anonymous)],
                            isAuthenticated: [Function(anonymous)],
                                isUnauthenticated: [Function(anonymous)],
                                    _sessionManager: SessionManager {
                  _key: 'passport',
                      _serializeUser: [Function: bound]
                [0]
        },
            _passport: { instance: [Authenticator] },
            user: {
                  _id: new ObjectId('65d788f7637ff4daa13ecd6d'),
                      email: 'antonio.torres@milenio.com',
                          nombre: 'Antonio',
                              password: '$2b$12$/Dz5rjDxTmTKiAVIR/HFn.NFe59aR0sucne912oStikcbs/uwih.O',
                                  __v: 0
                            [0]
        },
            flash: [Function: _flash],
                route: Route { path: '/editar-perfil', stack: [Array], methods: [Object] },
        [0][Symbol(shapeMode)]: true,
            [0][Symbol(kCapture)]: false,
                [0][Symbol(kHeaders)]: {
                  host: 'localhost:5000',
                      connection: 'keep-alive',
                          'content-length': '59',
                              'cache-control': 'max-age=0',
                                  'sec-ch-ua': '"Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"',
                                      'sec-ch-ua-mobile': '?0',
                                          'sec-ch-ua-platform': '"macOS"',
                                              'upgrade-insecure-requests': '1',
                                                  origin: 'http://localhost:5000',
                                                      'content-type': 'application/x-www-form-urlencoded',
                                                          'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
                                                              accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
                                                                  'sec-fetch-site': 'same-origin',
                                                                      'sec-fetch-mode': 'navigate',
                                                                          'sec-fetch-user': '?1',
                                                                              'sec-fetch-dest': 'document',
                                                                                  referer: 'http://localhost:5000/editar-perfil',
                                                                                      'accept-encoding': 'gzip, deflate, br, zstd',
                                                                                          'accept-language': 'es-419,es;q=0.9',
                                                                                              cookie: 'llavesecreta=s%3AGev6rQGoAych1bVULz7PpGYHg77FGg4f.tGxgkPI5r46xSkFnxDSyNdCflM3SADpKS1QqJ9GAZfg'
                                                                                        [0]
        },
        [0][Symbol(kHeadersCount)]: 40,
            [0][Symbol(kTrailers)]: null,
                [0][Symbol(kTrailersCount)]: 0
                [0]
    },
      _sent100: false,
          _expect_continue: false,
              _maxRequestsPerSocket: 0,
                  locals: [Object: null prototype] { mensajes: { } },
      writeHead: [Function: writeHead],
          end: [Function: end],
            [0][Symbol(shapeMode)]: false,
                [0][Symbol(kCapture)]: false,
                    [0][Symbol(kBytesWritten)]: 0,
                        [0][Symbol(kNeedDrain)]: false,
                            [0][Symbol(corked)]: 0,
                                [0][Symbol(kOutHeaders)]: [Object: null prototype] {
            'x-powered-by': ['X-Powered-By', 'Express']
        [0]
    },
    [0][Symbol(errored)]: null,
        [0][Symbol(kHighWaterMark)]: 16384,
            [0][Symbol(kRejectNonStandardBodyWrites)]: false,
                [0][Symbol(kUniqueHeaders)]: null
                [0]
}
